title: "Blue Theme Blog"
email: "you@example.com"
description: "Migrated from Blogger LinkMagz Template"
baseurl: "/linkmagz"
url: "https://bloghugo.github.io"

plugins:
  - jekyll-paginate

paginate: 5
paginate_path: "/page:num"

permalink: /:title

disqus_shortname: "belajarcorelweb"
