title: "Blue Theme Blog"
email: "siapxcom@gmail.com"
description: "Migrated from Blogger LinkMagz Template"
baseurl: "/linkmagz" 
url: "https://bloghugo.github.io"
theme: minima

# Plugins
plugins:
  - jekyll-paginate

# Pagination
paginate: 5
paginate_path: "/page:num"

# Disqus
disqus_shortname: "belajarcorelweb"
